/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weixin;

import java.awt.Color;

/**
 *
 * @author jerry
 */
public class sendingpanel extends javax.swing.JPanel {

    /**
     * Creates new form sendingpanel
     */
    public sendingpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sending_bar = new javax.swing.JProgressBar();
        sending_count = new javax.swing.JLabel();
        sending_over_button = new javax.swing.JButton();
        sending_stop_button = new javax.swing.JButton();
        sending_nick_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sending_result = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(609, 432));

        jLabel1.setText("发送进度:");

        sending_count.setText("0/100");

        sending_over_button.setBackground(new Color(233,233,233,0));
        sending_over_button.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        sending_over_button.setForeground(new java.awt.Color(255, 255, 255));
        sending_over_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_black.png"))); // NOI18N
        sending_over_button.setText("终止发送");
        sending_over_button.setBorder(null);
        sending_over_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sending_over_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sending_over_buttonActionPerformed(evt);
            }
        });

        sending_stop_button.setBackground(new Color(233,233,233,0));
        sending_stop_button.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        sending_stop_button.setForeground(new java.awt.Color(255, 255, 255));
        sending_stop_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_black.png"))); // NOI18N
        sending_stop_button.setText("暂停发送");
        sending_stop_button.setBorder(null);
        sending_stop_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setBorder(null);

        sending_result.setColumns(20);
        sending_result.setRows(5);
        sending_result.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane1.setViewportView(sending_result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sending_stop_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sending_over_button)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(sending_count)
                        .addGap(18, 18, 18)
                        .addComponent(sending_nick_name, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sending_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sending_nick_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(sending_count)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sending_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sending_over_button)
                    .addComponent(sending_stop_button))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 点击终止线程的事件
     * @param evt 
     */
    private void sending_over_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sending_over_buttonActionPerformed
        
    }//GEN-LAST:event_sending_over_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JProgressBar sending_bar;
    public javax.swing.JLabel sending_count;
    public javax.swing.JLabel sending_nick_name;
    public javax.swing.JButton sending_over_button;
    public javax.swing.JTextArea sending_result;
    public javax.swing.JButton sending_stop_button;
    // End of variables declaration//GEN-END:variables
}
